services:
  - type: web
    name: prok-frontend
    env: static
    buildCommand: cd app/frontend && npm install && npm run build
    staticPublishPath: app/frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://prok-professional-networking-t19l.onrender.com 