"""Add username to user model

Revision ID: 177027293749
Revises: 1b988d41ffec
Create Date: 2025-07-03 16:17:17.261764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177027293749'
down_revision = '1b988d41ffec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
