"""Add category, tags, likes, and views to Post model

Revision ID: add_category_tags_likes_views_to_posts
Revises: 72b414f9fd55
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_category_tags_likes_views_to_posts'
down_revision = '72b414f9fd55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True, default=0))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ### 